#!/bin/bash

echo "📂 Manual Gitea Repository Setup Instructions"
echo ""
echo "Since automated repository creation is restricted, please follow these steps:"
echo ""
echo "1. Open Gitea in your browser: http://gitea.local:8888"
echo "2. Login with: admin1 / admin123"
echo "3. Click the '+' button and select 'New Repository'"
echo "4. Fill in the details:"
echo "   - Repository name: Cloud-Native-Api"
echo "   - Description: Cloud-Native Gauntlet Infrastructure Repository"
echo "   - Make it public"
echo "   - Do NOT initialize with README"
echo "5. Click 'Create Repository'"
echo ""
echo "After creating the repository, run this command to push your code:"
echo ""
echo "git remote remove gitea 2>/dev/null || true"
echo "git remote add gitea http://admin1:admin123@gitea.local:8888/admin1/Cloud-Native-Api.git"
echo "git push gitea main"
echo ""
echo "This will restore all your workflows and infrastructure code to Gitea."
