#!/bin/bash

echo "🧹 Gitea Repository Cleanup and Manual Setup Guide"
echo ""
echo "✅ GitHub Push Completed Successfully!"
echo "Your code is now available at: https://github.com/nafisatou/Cloud-Native-Api"
echo ""
echo "📋 For Gitea repository creation (manual steps required):"
echo ""
echo "1. 🌐 Open: http://gitea.local:8888"
echo "2. 🔑 Login: admin1 / admin123"
echo "3. ➕ Click '+' button → 'New Repository'"
echo "4. 📝 Fill details:"
echo "   - Repository name: cloud-native-api"
echo "   - Description: Cloud-Native Gauntlet Infrastructure Repository"
echo "   - Visibility: Public"
echo "   - ❌ Do NOT initialize with README/gitignore/license"
echo "5. ✅ Click 'Create Repository'"
echo ""
echo "6. 📤 After creation, push with:"
echo "   git push gitea main"
echo ""
echo "🎯 Current Status:"
echo "✅ Keycloak configured (realm: cloud-native, client: todo-app)"
echo "✅ Previous workflows restored (.gitea/workflows/api-ci.yml)"
echo "✅ GitHub repository updated"
echo "⏳ Gitea repository creation pending (manual step)"
echo ""
echo "🔑 Important credentials:"
echo "- Keycloak: admin/admin"
echo "- Gitea: admin1/admin123"
echo "- Client Secret: WeT9Mn8XhSxmIpbCy6VRpCYwsMBJzagX"
