#!/bin/bash

echo "📋 Manual Repository Creation Instructions"
echo "=========================================="
echo ""
echo "1. Open Gitea in browser: http://gitea.local:8888"
echo "2. Login with: admin1 / admin123"
echo "3. Click '+' (New Repository) in top right"
echo ""
echo "Create Repository 1:"
echo "- Repository Name: cloud-native-infra"
echo "- Description: Infrastructure and Terraform files"
echo "- Visibility: Public"
echo "- Initialize: NO (uncheck all boxes)"
echo "- Click 'Create Repository'"
echo ""
echo "Create Repository 2:"
echo "- Repository Name: rust-api"  
echo "- Description: Rust API application"
echo "- Visibility: Public"
echo "- Initialize: NO (uncheck all boxes)"
echo "- Click 'Create Repository'"
echo ""
echo "After creating both repositories, run:"
echo "./push-separate-repos.sh"
echo ""
echo "Then set up the runner:"
echo "./setup-gitea-runner.sh"
