name: API CI - Build and Push Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: linux-amd64
    steps:
      - name: Build and push (no external actions)
        run: |
          set -euo pipefail
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          echo "Building tags: latest and sha-${SHORT_SHA}"
          docker build -t localhost:5000/cloud-native-gauntlet-api:latest \
                       -t localhost:5000/cloud-native-gauntlet-api:sha-${SHORT_SHA} \
                       ./app/rust-api
          docker push localhost:5000/cloud-native-gauntlet-api:latest
          docker push localhost:5000/cloud-native-gauntlet-api:sha-${SHORT_SHA}

      # Optional rollout (enable if kubectl is configured)
      # - name: Rollout restart (rust-api)
      #   run: kubectl -n cloud-native-gauntlet rollout restart deploy/rust-api




