name: CI Pipeline

on:
  push:
    branches: [ main, develop, gitea-setup ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: https://github.com/actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          app/rust-api/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check Rust formatting
      run: |
        cd app/rust-api
        cargo fmt --all -- --check

    - name: Run Clippy
      run: |
        cd app/rust-api
        cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: |
        cd app/rust-api
        cargo test --verbose

    - name: Build Docker image
      run: |
        cd app/rust-api
        docker build -t rust-api:${{ github.sha }} .

  deploy-notification:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Notify deployment
      run: |
        echo "🚀 Build completed successfully"
        echo "📦 Ready for deployment to Kubernetes cluster"
        echo "🔗 Commit: ${{ github.sha }}"
