apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rust-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nafisatou/Cloud-Native-Api.git
    targetRevision: HEAD
    path: app/rust-api/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-native-gauntlet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nafisatou/Cloud-Native-Api.git
    targetRevision: HEAD
    path: terraform
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
