name: Build and Deploy to Production

on:
  push:
    branches: [ main ]
    paths:
      - 'app/rust-api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/rust-api/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/rust-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build and test Rust API
      working-directory: ./app/rust-api
      run: |
        cargo build --release
        cargo test

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app/rust-api
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update ArgoCD Application
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Update the image tag in ArgoCD application manifest
        sed -i "s|image: .*rust-api:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${IMAGE_TAG:0:7}|g" argocd/applications/rust-api-app.yaml
        
        # Commit and push the changes
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add argocd/applications/rust-api-app.yaml
        git commit -m "🚀 Update rust-api image to ${IMAGE_TAG:0:7}
        
        Auto-deployed from GitHub Actions
        - Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${IMAGE_TAG:0:7}
        - Triggered by: ${{ github.actor }}
        - Commit: ${IMAGE_TAG}"
        git push

    - name: Notify ArgoCD
      run: |
        echo "✅ Image built and pushed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${{ github.sha }}"
        echo "🔄 ArgoCD will automatically sync within 3 minutes"
        echo "🌐 Check deployment at: http://argocd.local"
